#!/usr/bin/env bash
#
# qnap-tsx70 diagnostic bundle.
#
# Collects what a maintainer needs to answer an issue, and nothing else.
# Every line of output passes through redact(), which removes hostnames, IPv4
# and IPv6 addresses, MAC addresses, UUIDs and device serial numbers.
#
# Read the output before posting it. Redaction is a safety net, not a promise.

set -uo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "$(readlink -f -- "${BASH_SOURCE[0]}")")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"

CONF_FILE="${QNAP_TSX70_CONF:-/etc/qnap-tsx70-lcd.conf}"
STATE_DIR="/var/lib/qnap-tsx70"
# The redactor is a separate Python filter because compressed IPv6 addresses
# cannot be told apart from ordinary colon-separated text by a regex alone.
# Overridable so the regression suite can prove that a failing redactor makes
# this script fail rather than emit an unredacted bundle.
REDACTOR="${QNAP_TSX70_REDACT:-$SCRIPT_DIR/redact.py}"
OUTPUT=""
WITH_SMART=0

die() { printf 'error: %s\n' "$*" >&2; exit 1; }

usage() {
    cat <<'USAGE'
Usage: sudo ./scripts/diagnose.sh [options]

Options:
  -o, --output FILE   Write the bundle to FILE instead of stdout.
      --with-smart    Include per-disk SMART summaries (serials removed).
  -h, --help          Show this help.

The bundle is redacted: hostnames, IP and MAC addresses, UUIDs and disk
serial numbers are replaced with placeholders. Review it before posting.
USAGE
}

while [ $# -gt 0 ]; do
    case "$1" in
        -o|--output)
            # An unconsumed `-o` used to leave OUTPUT empty and silently print
            # the bundle to stdout instead.
            [ $# -ge 2 ] || { usage >&2; die "$1 requires a file argument"; }
            case "$2" in
                "") usage >&2; die "$1 requires a non-empty file argument" ;;
                -*) usage >&2; die "$1 requires a file argument, got: $2" ;;
            esac
            OUTPUT="$2"
            shift ;;
        --output=*)
            OUTPUT="${1#*=}"
            [ -n "$OUTPUT" ] || { usage >&2; die "--output requires a file argument"; } ;;
        --with-smart) WITH_SMART=1 ;;
        -h|--help) usage; exit 0 ;;
        *) usage >&2; die "unknown option: $1" ;;
    esac
    shift
done

[ -f "$REDACTOR" ] || die "redaction filter not found at $REDACTOR; refusing to \
produce an unredacted bundle"
command -v python3 >/dev/null 2>&1 || die "python3 is required to redact the bundle"

HOSTNAME_RAW="$(hostname 2>/dev/null || echo '')"
HOSTNAME_SHORT="${HOSTNAME_RAW%%.*}"

# redact - filter stdin through the tested Python redactor.
redact() {
    local args=()
    [ -n "$HOSTNAME_SHORT" ] && args+=(--hostname "$HOSTNAME_SHORT")
    if [ -n "$HOSTNAME_RAW" ] && [ "$HOSTNAME_RAW" != "$HOSTNAME_SHORT" ]; then
        args+=(--hostname "$HOSTNAME_RAW")
    fi
    python3 "$REDACTOR" ${args[@]+"${args[@]}"}
}

section() { printf '\n===== %s =====\n' "$1"; }
have() { command -v "$1" >/dev/null 2>&1; }

collect() {
    printf '# qnap-tsx70 diagnostic bundle (redacted)\n'
    printf '# Generated by scripts/diagnose.sh\n'

    section "System"
    if [ -r /etc/os-release ]; then
        # Only the distribution identity; nothing host-specific.
        grep -E '^(NAME|VERSION|VERSION_ID|ID)=' /etc/os-release || true
    fi
    printf 'kernel: %s\n' "$(uname -r 2>/dev/null)"
    printf 'arch:   %s\n' "$(uname -m 2>/dev/null)"

    section "Chassis"
    local f
    # Deliberately limited to model identity. product_uuid, board_serial and
    # chassis_serial are never read.
    for f in sys_vendor product_name board_vendor board_name; do
        [ -r "/sys/class/dmi/id/$f" ] && printf '%-14s %s\n' "$f:" "$(cat "/sys/class/dmi/id/$f")"
    done

    section "CPU and memory"
    grep -m1 '^model name' /proc/cpuinfo 2>/dev/null || true
    printf 'cores:  %s\n' "$(grep -c '^processor' /proc/cpuinfo 2>/dev/null)"
    grep -E '^Mem(Total|Available):' /proc/meminfo 2>/dev/null || true

    section "Project versions"
    for f in /usr/local/bin/qnap-tsx70-lcd /usr/local/bin/qnap-tsx70-fancontrol; do
        if [ -x "$f" ]; then
            printf '%s: %s\n' "$f" "$("$f" --version 2>&1 | head -1)"
        else
            printf '%s: not installed\n' "$f"
        fi
    done
    printf 'python3: %s\n' "$(python3 --version 2>&1)"
    have smartctl && printf 'smartctl: %s\n' "$(smartctl --version 2>&1 | head -1)"
    have lsblk && printf 'lsblk: %s\n' "$(lsblk --version 2>&1 | head -1)"

    section "Kernel modules"
    lsmod 2>/dev/null | grep -E '^(f71882fg|coretemp|8250|serial)' || printf 'none of f71882fg/coretemp loaded\n'

    section "Serial ports"
    ls -l /dev/ttyS* 2>/dev/null || printf 'no /dev/ttyS* devices\n'
    # Asking the binary keeps this agreeing with the runtime about quoting,
    # inline comments and duplicate keys instead of re-parsing the file here.
    local port lcd
    port=""
    for lcd in /usr/local/bin/qnap-tsx70-lcd "$REPO_ROOT/bin/qnap-tsx70-lcd"; do
        [ -f "$lcd" ] || continue
        port="$(python3 "$lcd" --config "$CONF_FILE" --print-config serial_port \
                2>/dev/null)" && [ -n "$port" ] && break
        port=""
    done
    if [ -z "$port" ]; then
        printf '\nconfigured port: unreadable (see the Configuration section)\n'
    else
        printf '\nconfigured port: %s\n' "$port"
        if [ -c "$port" ]; then
            printf 'exists: yes\n'
            have fuser && printf 'in use by: %s\n' "$(fuser "$port" 2>/dev/null || echo 'nothing')"
            have stty && printf 'stty: %s\n' "$(stty -F "$port" -a 2>&1 | head -1)"
        else
            printf 'exists: no\n'
        fi
    fi

    section "hwmon sensors"
    for f in /sys/class/hwmon/hwmon*; do
        [ -r "$f/name" ] || continue
        printf '%-28s %s\n' "$f" "$(cat "$f/name")"
    done

    section "Fan controller"
    local dev found=0
    for dev in /sys/devices/platform/f71882fg.*; do
        [ -d "$dev" ] || continue
        found=1
        printf 'device: %s\n' "$dev"
        local ch
        for ch in 1 2 3 4; do
            [ -r "$dev/fan${ch}_input" ] || continue
            printf '  fan%s rpm=%-6s pwm=%-5s enable=%s\n' "$ch" \
                "$(cat "$dev/fan${ch}_input" 2>/dev/null)" \
                "$(cat "$dev/pwm${ch}" 2>/dev/null || echo n/a)" \
                "$(cat "$dev/pwm${ch}_enable" 2>/dev/null || echo n/a)"
        done
    done
    [ "$found" -eq 0 ] && printf 'no f71882fg platform device found\n'

    section "Calibration state"
    if [ -f "$STATE_DIR/fan-calibration.json" ]; then
        cat "$STATE_DIR/fan-calibration.json"
    else
        printf 'no calibration at %s/fan-calibration.json\n' "$STATE_DIR"
    fi

    section "Configuration"
    if [ -f "$CONF_FILE" ]; then
        grep -vE '^[[:space:]]*(#|$)' "$CONF_FILE" || printf '(all defaults)\n'
    else
        printf '%s not present; built-in defaults are in use\n' "$CONF_FILE"
    fi

    section "Disks"
    if have lsblk; then
        # Serial numbers are deliberately not requested.
        lsblk -d -o NAME,SIZE,TYPE,TRAN,ROTA,MODEL 2>/dev/null
    else
        printf 'lsblk not available\n'
    fi

    if [ "$WITH_SMART" -eq 1 ] && have smartctl; then
        section "SMART summary"
        local d
        for d in /dev/sd? /dev/nvme?n?; do
            [ -b "$d" ] || continue
            printf '\n--- %s ---\n' "$d"
            smartctl -H -i "$d" 2>&1 | grep -vE -i 'serial|wwn|identifier' || true
        done
    fi

    section "Services"
    local unit
    for unit in qnap-tsx70-lcd qnap-tsx70-fancontrol; do
        printf '\n--- %s ---\n' "$unit"
        systemctl is-enabled "$unit" 2>&1 | sed 's/^/enabled: /'
        systemctl is-active "$unit" 2>&1 | sed 's/^/active:  /'
        systemctl status --no-pager --lines=0 "$unit" 2>&1 | head -8
    done

    section "Recent logs"
    for unit in qnap-tsx70-lcd qnap-tsx70-fancontrol; do
        printf '\n--- journalctl -u %s (last 40) ---\n' "$unit"
        journalctl -u "$unit" --no-pager --lines=40 -o cat 2>&1 | tail -40
    done

    section "Legacy artifacts"
    ls -l /etc/systemd/system/saturn-*.service /usr/local/bin/saturn-* \
          /etc/saturn-fan-cache.json 2>/dev/null || printf 'none found\n'

    printf '\n===== end of bundle =====\n'
}

if [ -z "$OUTPUT" ]; then
    collect 2>&1 | redact
    exit $?
fi

# Writing to a file is a transaction: a temporary file next to the target, a
# collection and a redaction that both have to succeed, mode 0600, and only
# then an atomic rename. Success is announced after the file exists, never
# before - the old order could print "Wrote..." and exit zero having written
# nothing at all.
[ -d "$OUTPUT" ] && die "output path is a directory: $OUTPUT"
OUT_DIR="$(dirname -- "$OUTPUT")"
[ -d "$OUT_DIR" ] || die "output directory does not exist: $OUT_DIR"

TMP_OUT="$(mktemp -- "$OUT_DIR/.qnap-tsx70-diagnose.XXXXXX" 2>/dev/null)" \
    || die "cannot create a temporary file in $OUT_DIR"
cleanup_tmp() { [ -n "${TMP_OUT:-}" ] && rm -f -- "$TMP_OUT"; }
trap 'cleanup_tmp' EXIT HUP INT TERM

collect 2>&1 | redact > "$TMP_OUT" \
    || die "collection or redaction failed; $OUTPUT was not written"
chmod 0600 -- "$TMP_OUT" || die "cannot set mode 0600 on the bundle"
mv -f -- "$TMP_OUT" "$OUTPUT" || die "cannot move the bundle into place: $OUTPUT"
TMP_OUT=""
trap - EXIT HUP INT TERM

printf 'Wrote redacted bundle to %s\n' "$OUTPUT" >&2
printf 'Review it before attaching it to an issue.\n' >&2
