#!/usr/bin/env bash
#
# qnap-tsx70 diagnostic bundle.
#
# Collects what a maintainer needs to answer an issue, and nothing else.
# Every line of output passes through redact(), which removes hostnames, IPv4
# and IPv6 addresses, MAC addresses, UUIDs and device serial numbers.
#
# Read the output before posting it. Redaction is a safety net, not a promise.

set -uo pipefail

CONF_FILE="${QNAP_TSX70_CONF:-/etc/qnap-tsx70-lcd.conf}"
STATE_DIR="/var/lib/qnap-tsx70"
OUTPUT=""
WITH_SMART=0

usage() {
    cat <<'USAGE'
Usage: sudo ./scripts/diagnose.sh [options]

Options:
  -o, --output FILE   Write the bundle to FILE instead of stdout.
      --with-smart    Include per-disk SMART summaries (serials removed).
  -h, --help          Show this help.

The bundle is redacted: hostnames, IP and MAC addresses, UUIDs and disk
serial numbers are replaced with placeholders. Review it before posting.
USAGE
}

while [ $# -gt 0 ]; do
    case "$1" in
        -o|--output) OUTPUT="${2:-}"; shift ;;
        --with-smart) WITH_SMART=1 ;;
        -h|--help) usage; exit 0 ;;
        *) usage >&2; exit 1 ;;
    esac
    shift
done

HOSTNAME_RAW="$(hostname 2>/dev/null || echo '')"
HOSTNAME_SHORT="${HOSTNAME_RAW%%.*}"

# redact - filter stdin, removing identifying values.
redact() {
    local script=''
    if [ -n "$HOSTNAME_SHORT" ]; then
        local escaped
        escaped="$(printf '%s' "$HOSTNAME_SHORT" | sed 's/[][\.*^$/&]/\\&/g')"
        # Word-anchored: a short hostname must not be substituted inside an
        # unrelated identifier such as a board model number.
        script+="s/\\b${escaped}\\b/[hostname]/Ig;"
    fi
    sed -E "
        ${script}
        s/\b([0-9a-fA-F]{2}:){5}[0-9a-fA-F]{2}\b/[mac]/g;
        s/\b([0-9]{1,3}\.){3}[0-9]{1,3}(\/[0-9]{1,2})?\b/[ip]/g;
        s/\b([0-9a-fA-F]{4}:){2,7}[0-9a-fA-F]{0,4}(:[0-9a-fA-F]{0,4})*\b/[ipv6]/g;
        s/\b[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\b/[uuid]/Ig;
        s/^(.*([Ss]erial [Nn]umber|SERIAL|[Ss]erial#|LU WWN|WWN|IEEE EUI-64|[Ww]orld [Ww]ide [Nn]ame).*)$/[serial removed]/;
        s/\"serial_number\"[[:space:]]*:[[:space:]]*\"[^\"]*\"/\"serial_number\": \"[serial removed]\"/g;
        s/(PARTUUID|UUID|ID_SERIAL|WWN)=[^[:space:]\"]*/\1=[redacted]/Ig;
    "
}

section() { printf '\n===== %s =====\n' "$1"; }
have() { command -v "$1" >/dev/null 2>&1; }

collect() {
    printf '# qnap-tsx70 diagnostic bundle (redacted)\n'
    printf '# Generated by scripts/diagnose.sh\n'

    section "System"
    if [ -r /etc/os-release ]; then
        # Only the distribution identity; nothing host-specific.
        grep -E '^(NAME|VERSION|VERSION_ID|ID)=' /etc/os-release || true
    fi
    printf 'kernel: %s\n' "$(uname -r 2>/dev/null)"
    printf 'arch:   %s\n' "$(uname -m 2>/dev/null)"

    section "Chassis"
    local f
    # Deliberately limited to model identity. product_uuid, board_serial and
    # chassis_serial are never read.
    for f in sys_vendor product_name board_vendor board_name; do
        [ -r "/sys/class/dmi/id/$f" ] && printf '%-14s %s\n' "$f:" "$(cat "/sys/class/dmi/id/$f")"
    done

    section "CPU and memory"
    grep -m1 '^model name' /proc/cpuinfo 2>/dev/null || true
    printf 'cores:  %s\n' "$(grep -c '^processor' /proc/cpuinfo 2>/dev/null)"
    grep -E '^Mem(Total|Available):' /proc/meminfo 2>/dev/null || true

    section "Project versions"
    for f in /usr/local/bin/qnap-tsx70-lcd /usr/local/bin/qnap-tsx70-fancontrol; do
        if [ -x "$f" ]; then
            printf '%s: %s\n' "$f" "$("$f" --version 2>&1 | head -1)"
        else
            printf '%s: not installed\n' "$f"
        fi
    done
    printf 'python3: %s\n' "$(python3 --version 2>&1)"
    have smartctl && printf 'smartctl: %s\n' "$(smartctl --version 2>&1 | head -1)"
    have lsblk && printf 'lsblk: %s\n' "$(lsblk --version 2>&1 | head -1)"

    section "Kernel modules"
    lsmod 2>/dev/null | grep -E '^(f71882fg|coretemp|8250|serial)' || printf 'none of f71882fg/coretemp loaded\n'

    section "Serial ports"
    ls -l /dev/ttyS* 2>/dev/null || printf 'no /dev/ttyS* devices\n'
    local port
    port=""
    if [ -r "$CONF_FILE" ]; then
        port="$(sed -n 's/^[[:space:]]*serial_port[[:space:]]*=[[:space:]]*//p' "$CONF_FILE" | tail -1)" || port=""
    fi
    port="${port:-/dev/ttyS1}"
    printf '\nconfigured port: %s\n' "$port"
    if [ -c "$port" ]; then
        printf 'exists: yes\n'
        have fuser && printf 'in use by: %s\n' "$(fuser "$port" 2>/dev/null || echo 'nothing')"
        have stty && printf 'stty: %s\n' "$(stty -F "$port" -a 2>&1 | head -1)"
    else
        printf 'exists: no\n'
    fi

    section "hwmon sensors"
    for f in /sys/class/hwmon/hwmon*; do
        [ -r "$f/name" ] || continue
        printf '%-28s %s\n' "$f" "$(cat "$f/name")"
    done

    section "Fan controller"
    local dev found=0
    for dev in /sys/devices/platform/f71882fg.*; do
        [ -d "$dev" ] || continue
        found=1
        printf 'device: %s\n' "$dev"
        local ch
        for ch in 1 2 3 4; do
            [ -r "$dev/fan${ch}_input" ] || continue
            printf '  fan%s rpm=%-6s pwm=%-5s enable=%s\n' "$ch" \
                "$(cat "$dev/fan${ch}_input" 2>/dev/null)" \
                "$(cat "$dev/pwm${ch}" 2>/dev/null || echo n/a)" \
                "$(cat "$dev/pwm${ch}_enable" 2>/dev/null || echo n/a)"
        done
    done
    [ "$found" -eq 0 ] && printf 'no f71882fg platform device found\n'

    section "Calibration state"
    if [ -f "$STATE_DIR/fan-calibration.json" ]; then
        cat "$STATE_DIR/fan-calibration.json"
    else
        printf 'no calibration at %s/fan-calibration.json\n' "$STATE_DIR"
    fi

    section "Configuration"
    if [ -f "$CONF_FILE" ]; then
        grep -vE '^[[:space:]]*(#|$)' "$CONF_FILE" || printf '(all defaults)\n'
    else
        printf '%s not present; built-in defaults are in use\n' "$CONF_FILE"
    fi

    section "Disks"
    if have lsblk; then
        # Serial numbers are deliberately not requested.
        lsblk -d -o NAME,SIZE,TYPE,TRAN,ROTA,MODEL 2>/dev/null
    else
        printf 'lsblk not available\n'
    fi

    if [ "$WITH_SMART" -eq 1 ] && have smartctl; then
        section "SMART summary"
        local d
        for d in /dev/sd? /dev/nvme?n?; do
            [ -b "$d" ] || continue
            printf '\n--- %s ---\n' "$d"
            smartctl -H -i "$d" 2>&1 | grep -vE -i 'serial|wwn|identifier' || true
        done
    fi

    section "Services"
    local unit
    for unit in qnap-tsx70-lcd qnap-tsx70-fancontrol; do
        printf '\n--- %s ---\n' "$unit"
        systemctl is-enabled "$unit" 2>&1 | sed 's/^/enabled: /'
        systemctl is-active "$unit" 2>&1 | sed 's/^/active:  /'
        systemctl status --no-pager --lines=0 "$unit" 2>&1 | head -8
    done

    section "Recent logs"
    for unit in qnap-tsx70-lcd qnap-tsx70-fancontrol; do
        printf '\n--- journalctl -u %s (last 40) ---\n' "$unit"
        journalctl -u "$unit" --no-pager --lines=40 -o cat 2>&1 | tail -40
    done

    section "Legacy artifacts"
    ls -l /etc/systemd/system/saturn-*.service /usr/local/bin/saturn-* \
          /etc/saturn-fan-cache.json 2>/dev/null || printf 'none found\n'

    printf '\n===== end of bundle =====\n'
}

if [ -n "$OUTPUT" ]; then
    collect 2>&1 | redact > "$OUTPUT"
    chmod 0600 "$OUTPUT" 2>/dev/null || true
    printf 'Wrote redacted bundle to %s\n' "$OUTPUT" >&2
    printf 'Review it before attaching it to an issue.\n' >&2
else
    collect 2>&1 | redact
fi
